# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser.
# Manual edits will be overwritten on the next release.
class Cascade < Formula
  desc "Cascade CLI - Connect your local MCP server to Cascade Market"
  homepage "https://cascade.fyi"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cascade-protocol/splits/releases/download/v0.1.0/cascade_0.1.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_arm do
      url "https://github.com/cascade-protocol/splits/releases/download/v0.1.0/cascade_0.1.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cascade-protocol/splits/releases/download/v0.1.0/cascade_0.1.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_arm do
      url "https://github.com/cascade-protocol/splits/releases/download/v0.1.0/cascade_0.1.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "cascade"
  end

  test do
    system "#{bin}/cascade", "--version"
  end
end
