# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cascade < Formula
  desc "Cascade CLI - Connect your local MCP server to Cascade Market"
  homepage "https://cascade.fyi"
  version "cli-v0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cascade-protocol/splits/releases/download/cli-v0.1.0/cascade_cli-v0.1.0_darwin_amd64.tar.gz"
      sha256 "c1935015619e924b526f63511c6e1d012e5ae279bba544c0235df1e11bc32054"

      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cascade-protocol/splits/releases/download/cli-v0.1.0/cascade_cli-v0.1.0_darwin_arm64.tar.gz"
      sha256 "9188e0642db872db70a41cfcf5533f32d13d252a10d1a3921e1a496a92fc7327"

      def install
        bin.install "cascade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cascade-protocol/splits/releases/download/cli-v0.1.0/cascade_cli-v0.1.0_linux_amd64.tar.gz"
      sha256 "8a7f496268dc3a1f43a4132960d4585ba91919b31cb4915b497aca62182be708"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cascade-protocol/splits/releases/download/cli-v0.1.0/cascade_cli-v0.1.0_linux_arm64.tar.gz"
      sha256 "14e03ae06bbd8aeb80f1c13ac34e89a1f126883de73694e5ff3db1af67288c5d"
      def install
        bin.install "cascade"
      end
    end
  end

  test do
    system "#{bin}/cascade", "--version"
  end
end
